# Firebase Hosting Deployment Workflow
name: Deploy to Firebase Hosting on PR or Develop Merge

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm run ci
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PELE_5BE0C }}
          channelId: ${{ github.ref_name }}
          projectId: pele-5be0c